"""empty message

Revision ID: 0ed290e4d2bd
Revises: d07ca4141b4e
Create Date: 2023-05-08 11:02:20.903431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed290e4d2bd'
down_revision = 'd07ca4141b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_comment', schema=None) as batch_op:
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
