"""empty message

Revision ID: a3678c2efa29
Revises: a07315e5d13c
Create Date: 2023-05-06 09:29:12.995965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3678c2efa29'
down_revision = 'a07315e5d13c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', sa.String(length=100), nullable=False))

    with op.batch_alter_table('lawyer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lawyer', schema=None) as batch_op:
        batch_op.drop_column('province')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('province')

    # ### end Alembic commands ###
