"""empty message

Revision ID: ad4a5cc0d082
Revises: 1ccdc23f7906
Create Date: 2023-05-04 10:14:10.496789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad4a5cc0d082'
down_revision = '1ccdc23f7906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    with op.batch_alter_table('lawyer', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint('question_lawyer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['lawyer_id'], ['id'])

    with op.batch_alter_table('question_comment', schema=None) as batch_op:
        batch_op.drop_constraint('question_comment_id_user_fkey', type_='foreignkey')
        batch_op.drop_column('id_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('question_comment_id_user_fkey', 'user', ['id_user'], ['id'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('question_lawyer_id_fkey', 'lawyer', ['lawyer_id'], ['id'])

    with op.batch_alter_table('lawyer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.VARCHAR(length=250), autoincrement=False, nullable=True))

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.VARCHAR(length=250), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
