"""empty message

Revision ID: cffd5e25971b
Revises: fcfabdfe373f
Create Date: 2023-05-03 08:45:56.159291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cffd5e25971b'
down_revision = 'fcfabdfe373f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('review_company_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['company_user_id'], ['id'])
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('review_company_id_fkey', 'company', ['company_id'], ['id'])
        batch_op.drop_column('company_user_id')

    # ### end Alembic commands ###
