"""empty message

Revision ID: d7adc8c4b258
Revises: 0ed290e4d2bd
Create Date: 2023-05-08 11:04:37.710283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7adc8c4b258'
down_revision = '0ed290e4d2bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=True))
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
