"""empty message

Revision ID: fcfabdfe373f
Revises: b13ba581eebc
Create Date: 2023-05-01 08:16:14.466534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fcfabdfe373f'
down_revision = 'b13ba581eebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_comment')
    op.drop_table('lawyer_review_comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lawyer_review_comment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_lawyer_review', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_create', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_lawyer_review'], ['lawyer_review.id'], name='lawyer_review_comment_id_lawyer_review_fkey'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name='lawyer_review_comment_id_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='lawyer_review_comment_pkey')
    )
    op.create_table('review_comment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_review', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_create', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_review'], ['review.id'], name='review_comment_id_review_fkey'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name='review_comment_id_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='review_comment_pkey')
    )
    # ### end Alembic commands ###
